# Generated by Django 3.1.4 on 2021-03-06 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headlines',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='headlines',
            name='id',
        ),
        migrations.AddField(
            model_name='companies',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headlines',
            name='company_id',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_api.companies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
