# Generated by Django 3.1.4 on 2020-12-31 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('company_name', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('date_posted', models.DateField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('score', models.FloatField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.companies')),
            ],
        ),
    ]
