# Generated by Django 3.1.4 on 2020-12-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='goal',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='department',
            name='purpose',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='department',
            name='route',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
